### ISSUE TITLE
Compatibility with Userscripts Safari

### ISSUE THREAD

**Issue by draarong** [iFelix18/Trakt-Userscripts#154]
Compatibility check:
- [x] Profile image on Trakt
- [x] Ratings on Trakt
- [x] Stats for Trakt
- [x] Trakt Search
- [x] Translate Trakt

### Discussed in https://github.com/iFelix18/Trakt-Userscripts/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **draarong** February 15, 2022</sup>
If I use the Tampermonkey extension (on Safari for Mac), I'm able to enter the OMDB API key. But if I use the userscripts extension (which I want to do to sync scripts with Safari on iPhone), it neither asks automatically nor gives a way I can find to get to the config screen. Am I missing something?</div>

**Comment by iFelix18** [comment]
After a first investigation:

1.  I need to change `@inject-into` from `page` to `content`, scripts seem to continue to work fine on both Violentmonkey and Userscripts (to be tested with other userscript managers).

```diff
	// @run-at          document-start
-	// @inject-into     page
+	// @inject-into     content
	// ==/UserScript==
```
2. I need to change the IDs of all the instances of `GM_config` (this will result in having to configure all the scripts again at the new update), with the same ID there is a continuous overwriting of configurations between the various scripts of the same page.
```diff
	GM_config.init({
-		id: 'trakt-config',
+		id: 'ratings-on-trakt',
    	title: `${GM.info.script.name} v${GM.info.script.version} Settings`,
```
3. The 'GM.info' API is missing. It is implemented in v4.1, currently in beta, but it is a function `GM.info()` instead of an object `GM.info`. In addition, it does not return the author `GM.info.script.author`.
4. The 'GM.registerMenuCommand' API is missing.

**Comment by iFelix18** [comment]
I have updated all the scripts. Userscripts v4.1, currently in beta, is required.

Everything seems to work fine, however the script settings page, after the first configuration, cannot be called due to the missing `GM.registerMenuCommand`, I'm looking for a fix.

**Comment by draarong** [comment]
Thank you for the prompt work!

**Comment by iFelix18** [comment]
> the script settings page, after the first configuration, cannot be called due to the missing `GM.registerMenuCommand`, I'm looking for a fix.

The script settings page, in addition to `GM.registerMenuCommand`, can now be called with a link in the user menu.
For example:
![example](https://user-images.githubusercontent.com/19800006/155640213-eda66ef1-2402-4227-87d0-38020070bfa9.png)
